name: build and upload to pypi

on:
  push:
    branches:
      - master
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: 'json'
      - name: test
        run: |
          echo '${{ steps.file_changes.outputs.files_modified }}'
      - uses: actions/checkout@v2
        if:
          contains(steps.file_changes.outputs.files_modified, 'VERSION')
      - uses: actions/setup-python@v2
        if:
          contains(steps.file_changes.outputs.files_modified, 'VERSION')
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create a source package and upload it to pypi
        if:
          contains(steps.file_changes.outputs.files_modified, 'VERSION')
        run: |
          python setup.py sdist
          # debug
          pip install --upgrade wheel
          pip install --upgrade setuptools
          pip install --upgrade twine
          pip list | grep wheel
          pip list | grep setuptools
          pip list | grep twine
          python -m twine upload -u "__token__" -p "${{ secrets.pypi_token }}" dist/*
        # BUG: none of these two works correctly with long description in markdown :(
#      - name: Publish a source package to PyPI
#        if:
#          contains(steps.file_changes.outputs.files_modified, 'VERSION')
#        uses: pypa/gh-action-pypi-publish@master
#        uses: ortega2247/pypi-upload-action@master
#        with:
#          user: __token__
#          password: ${{ secrets.pypi_token }}
